### ISSUE TITLE
Please update gcc to the latest version

### ISSUE THREAD

**Issue by ITzTravelInTime** [nativeos/homebrew-i386-elf-toolchain#7] opened 2020-02-13 03:17 UTC
Hi, i have created a program which requires gcc 9 to be compiled and so this formula doesn't allow me to do it since it's gcc is on version 7, so i needed to create my own fork to do it, here it is: https://github.com/ITzTravelInTime/homebrew-i386-elf-toolchain/

please update your repo, so i don't need to work and then tap

**Comment by danirod** [comment] 2020-02-13 06:25
Okay, the thing is that I soft-deprecated this repo last year because i386-elf-gcc and i386-elf-binutils landed in homebrew-core with bottles to make the installation process smoother.

However, it seems that they have changed the formula recently to add x86_64 support in https://github.com/Homebrew/homebrew-core/pull/47935, so the binaries are renamed to x86_64-elf-gcc but they claim that it is still multilib so it should be able to provide i386-elf binaries too.

Anyway, I haven't got time to test this on my own 32-bit toy kernel so I don't know at this moment if this is a real regression for building 32 bit ELF images. Therefore I cannot trust the homebrew-core formula at the moment. Therefore it might not be the best moment to fully-deprecate this repo.

Would you be willing to send a pull request to merge your updated formulas upstream?

**Comment by danirod** [comment] 2020-02-13 08:35
> Would you be willing to send a pull request to merge your updated formulas upstream?

Nevermind, I did not know that I, as the upstream author, can open pull requests based on forks of the repo itself. I'll merge this myself.

Thanks for the heads up!

**Closed as completed** 2020-02-13 08:38 UTC

**Comment by ITzTravelInTime** [comment] 2020-02-13 12:27
Thank your for the update, and wiredly enought homebrew defaulted to your repo when i wanted to install i386-elf-gcc and i386-elf-binutils, since the formula has been officially replaced with x86_64-elf-gcc x86_64-elf-binutils
